#!/usr/bin/env python3
"""Download missing PDFs from arXiv API and mark has_pdf=True.

Reads data/orphan_pdfs.txt (generated by repair_has_pdf.py), downloads each
PDF from https://arxiv.org/pdf/{id}.pdf, writes to the paper directory,
and partial_updates has_pdf=True.

Usage:
  python scripts/download_missing_pdfs.py                # full run
  python scripts/download_missing_pdfs.py --dry-run      # first 100
  python scripts/download_missing_pdfs.py --workers 30   # control concurrency
"""

from __future__ import annotations

import argparse
import multiprocessing
import sqlite3
import subprocess
import time
from pathlib import Path

import structlog

from compass.logging import configure_logging
from compass.storage import storage
from compass.store.client import _WRITE_LOCK, _resolve_uri

# ── Constants ────────────────────────────────────────────────────────────────

ORPHAN_FILE = Path(
    "/inspire/hdd/project/multi-agent/niexiaohang-25130061/academic-compass/data/orphan_pdfs.txt"
)
CHECKPOINT_DB = Path(__file__).resolve().parent / "arxiv_dl_checkpoint.db"
DEFAULT_WORKERS = 40
MILVUS_BATCH = 100
PROGRESS_INTERVAL = 300  # seconds

logger = structlog.get_logger(__name__)


# ── Load workload ─────────────────────────────────────────────────────────────


def _load_orphans() -> list[tuple[str, str]]:
    """Parse orphan_pdfs.txt → list of (arxiv_id, dest_path)."""
    orphans: list[tuple[str, str]] = []
    with open(ORPHAN_FILE) as f:
        header = f.readline()  # skip header
        print(f"Header: {header.strip()}")
        for line in f:
            line = line.strip()
            if not line:
                continue
            parts = line.split("\t")
            if len(parts) >= 2:
                orphans.append((parts[0], parts[1]))
    logger.info("loaded orphans", count=len(orphans))
    return orphans


# ── Download ──────────────────────────────────────────────────────────────────


def _curl_download(arxiv_id: str, dest: str) -> bool:
    """Download PDF from arXiv via curl -L (follow redirect)."""
    dest_path = Path(dest)
    dest_path.parent.mkdir(parents=True, exist_ok=True)
    url = f"https://arxiv.org/pdf/{arxiv_id}.pdf"
    try:
        subprocess.run(
            [
                "curl",
                "-sSL",
                "-o",
                str(dest_path),
                "--connect-timeout",
                "10",
                "--max-time",
                "120",
                url,
            ],
            check=True,
            capture_output=True,
            timeout=130,
        )
        return dest_path.stat().st_size > 0
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired):
        if dest_path.exists():
            dest_path.unlink(missing_ok=True)
        return False


def _pdf_ok(dest: str) -> bool:
    """Verify the downloaded PDF has a valid header and is not too small."""
    dest_path = Path(dest)
    if not dest_path.exists():
        return False
    size = dest_path.stat().st_size
    if size < 512:
        return False
    try:
        with open(dest_path, "rb") as fh:
            header = fh.read(5)
        return header.startswith(b"%PDF")
    except OSError:
        return False


def _download_one(args: tuple[int, str, str, bool]) -> tuple[int, bool]:
    """Worker entry: download + verify one paper."""
    idx, arxiv_id, dest, dry_run = args

    # Skip if already exists and is valid
    if _pdf_ok(dest):
        return idx, True

    if dry_run:
        return idx, False

    if _curl_download(arxiv_id, dest) and _pdf_ok(dest):
        return idx, True

    logger.warning("download failed", arxiv_id=arxiv_id)
    return idx, False


# ── Checkpoint ────────────────────────────────────────────────────────────────


def _open_checkpoint(path: Path) -> sqlite3.Connection:
    path.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(str(path))
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("CREATE TABLE IF NOT EXISTS done (arxiv_id TEXT PRIMARY KEY)")
    conn.commit()
    return conn


def _load_done(conn: sqlite3.Connection) -> set[str]:
    return {r[0] for r in conn.execute("SELECT arxiv_id FROM done").fetchall()}


def _mark_done(conn: sqlite3.Connection, arxiv_id: str) -> None:
    conn.execute("INSERT OR IGNORE INTO done(arxiv_id) VALUES (?)", (arxiv_id,))
    conn.commit()


# ── Milvus update ─────────────────────────────────────────────────────────────


def _batch_update(arxiv_ids: list[str]) -> int:
    import pymilvus

    client = pymilvus.MilvusClient(uri=_resolve_uri(), timeout=30)
    total = 0
    for i in range(0, len(arxiv_ids), MILVUS_BATCH):
        batch = arxiv_ids[i : i + MILVUS_BATCH]
        try:
            with _WRITE_LOCK:
                result = client.upsert(
                    "arxiv_papers",
                    data=[{"arxiv_id": aid, "has_pdf": True} for aid in batch],
                    partial_update=True,
                )
                total += result.get("upsert_count", len(batch))
        except Exception as exc:
            logger.error("milvus update failed", batch=i, error=str(exc)[:200])
    return total


# ── Main ─────────────────────────────────────────────────────────────────────


def main() -> None:
    parser = argparse.ArgumentParser(description="Download missing PDFs from arXiv.")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--workers", type=int, default=DEFAULT_WORKERS)
    args = parser.parse_args()

    log_path = storage.log_path("arxiv_dl", "download_missing.log")
    configure_logging(log_level="INFO", use_json=True, file_handler=(str(log_path), 100_000_000, 5))

    # Load + resume
    all_orphans = _load_orphans()
    ck = _open_checkpoint(CHECKPOINT_DB)
    done = _load_done(ck)
    todo = [(aid, dest) for aid, dest in all_orphans if aid not in done]
    logger.info("workload", total=len(all_orphans), done=len(done), todo=len(todo))

    if args.dry_run:
        todo = todo[:100]

    if not todo:
        logger.info("nothing to do")
        ck.close()
        return

    # Parallel download
    tasks = [(i, aid, dest, args.dry_run) for i, (aid, dest) in enumerate(todo)]
    max_idx = len(todo) - 1
    downloaded: list[str] = []
    stats = {"total": len(all_orphans), "ok": len(done), "failed": 0, "milvus": 0}
    t0 = time.monotonic()

    with multiprocessing.Pool(processes=args.workers) as pool:
        for idx, ok in pool.imap_unordered(_download_one, tasks, chunksize=50):
            aid = todo[idx][0]
            if ok:
                _mark_done(ck, aid)
                downloaded.append(aid)
                stats["ok"] += 1
            else:
                stats["failed"] += 1

            # Flush Milvus
            if len(downloaded) >= MILVUS_BATCH:
                stats["milvus"] += _batch_update(downloaded)
                downloaded = []

            elapsed = time.monotonic() - t0
            if elapsed >= PROGRESS_INTERVAL or idx >= max_idx:
                remaining = stats["total"] - stats["ok"]
                rate = (stats["ok"] - len(done)) / elapsed if elapsed > 0 else 0
                logger.info(
                    "progress",
                    ok=stats["ok"],
                    failed=stats["failed"],
                    milvus=stats["milvus"],
                    elapsed_m=f"{elapsed / 60:.1f}",
                    rate_s=f"{rate:.1f}",
                    eta_h=f"{remaining / rate / 3600:.1f}" if rate > 0 else "N/A",
                )
                t0 = time.monotonic()

    # Final flush
    if downloaded:
        stats["milvus"] += _batch_update(downloaded)

    ck.close()
    logger.info("download complete", **stats)
    print(f"\nDownloaded: {stats['ok']}  Failed: {stats['failed']}  Milvus: {stats['milvus']}")


if __name__ == "__main__":
    main()
