/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/admin/analytics/overview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Analytics Overview */
    get: operations["analytics_overview_admin_analytics_overview_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/audit-events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Audit Events */
    get: operations["audit_events_admin_audit_events_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/capabilities": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Capabilities */
    get: operations["capabilities_admin_capabilities_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/operations/overview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Operations Overview */
    get: operations["operations_overview_admin_operations_overview_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/users/lookup": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lookup User */
    get: operations["lookup_user_admin_users_lookup_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/users/{user_id}/quota-overrides": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update Quota Overrides */
    put: operations["update_quota_overrides_admin_users__user_id__quota_overrides_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/change-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Change Password */
    post: operations["change_password_auth_change_password_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/forgot-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Forgot Password */
    post: operations["_forgot_password_auth_forgot_password_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations["_login_auth_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout */
    post: operations["logout_auth_logout_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Refresh Cookie */
    post: operations["_refresh_cookie_auth_refresh_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register */
    post: operations["_register_auth_register_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/resend-verification": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Resend Verification */
    post: operations["_resend_verification_auth_resend_verification_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/reset-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reset Password */
    post: operations["_reset_password_auth_reset_password_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/sessions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Sessions */
    get: operations["get_sessions_auth_sessions_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/sessions/revoke-others": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Revoke Others */
    post: operations["revoke_others_auth_sessions_revoke_others_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/sessions/{session_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete Session */
    delete: operations["delete_session_auth_sessions__session_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/verify-email": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Verify Email */
    post: operations["verify_email_auth_verify_email_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/capabilities": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Capabilities
     * @description Return fail-closed, non-user-specific product capabilities.
     */
    get: operations["get_capabilities_capabilities_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/extract": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Extract */
    post: operations["extract_extract_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/livez": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Livez */
    get: operations["livez_livez_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/readyz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Readyz */
    get: operations["readyz_readyz_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Search */
    post: operations["search_search_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/search/history": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List History */
    get: operations["list_history_search_history_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/search/history/bulk-delete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Bulk Delete History */
    post: operations["bulk_delete_history_search_history_bulk_delete_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/search/history/{entry_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete History Entry */
    delete: operations["delete_history_entry_search_history__entry_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/surveys": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Surveys */
    get: operations["surveys_surveys_get"];
    put?: never;
    /** Submit Survey */
    post: operations["submit_survey_surveys_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/surveys/{survey_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Survey */
    get: operations["survey_surveys__survey_id__get"];
    put?: never;
    post?: never;
    /** Remove Survey */
    delete: operations["remove_survey_surveys__survey_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/surveys/{survey_id}/artifacts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Survey Artifacts */
    get: operations["survey_artifacts_surveys__survey_id__artifacts_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/surveys/{survey_id}/cancel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Cancel Survey Request */
    post: operations["cancel_survey_request_surveys__survey_id__cancel_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/surveys/{survey_id}/download": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Survey Report Download */
    get: operations["survey_report_download_surveys__survey_id__download_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/surveys/{survey_id}/drafts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Survey Drafts */
    get: operations["survey_drafts_surveys__survey_id__drafts_get"];
    put?: never;
    /** Revise Survey Draft */
    post: operations["revise_survey_draft_surveys__survey_id__drafts_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/surveys/{survey_id}/drafts/manual": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Add Manual Survey Draft */
    post: operations["add_manual_survey_draft_surveys__survey_id__drafts_manual_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/surveys/{survey_id}/progress": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Survey Progress */
    get: operations["survey_progress_surveys__survey_id__progress_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/surveys/{survey_id}/report": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Survey Report */
    get: operations["survey_report_surveys__survey_id__report_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/surveys/{survey_id}/start": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Start Survey Execution */
    post: operations["start_survey_execution_surveys__survey_id__start_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/user/access-keys": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Keys */
    get: operations["get_keys_user_access_keys_get"];
    put?: never;
    /** Create Key */
    post: operations["create_key_user_access_keys_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/user/access-keys/{key_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete Key */
    delete: operations["delete_key_user_access_keys__key_id__delete"];
    options?: never;
    head?: never;
    /** Patch Key */
    patch: operations["patch_key_user_access_keys__key_id__patch"];
    trace?: never;
  };
  "/user/avatar": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Avatar */
    get: operations["get_avatar_user_avatar_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/user/profile": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Profile */
    get: operations["get_profile_user_profile_get"];
    /** Update Profile */
    put: operations["_update_profile_user_profile_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Profile */
    patch: operations["_update_profile_user_profile_patch"];
    trace?: never;
  };
  "/user/usage/export.csv": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Usage Export */
    get: operations["usage_export_user_usage_export_csv_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/user/usage/latency": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Usage Latency */
    get: operations["usage_latency_user_usage_latency_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/user/usage/records": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Usage Records */
    get: operations["usage_records_user_usage_records_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/user/usage/summary": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Usage Summary */
    get: operations["usage_summary_user_usage_summary_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/user/usage/volume": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Usage Volume */
    get: operations["usage_volume_user_usage_volume_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AccessKeyResponse */
    AccessKeyResponse: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Expires At */
      expires_at: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Last4 */
      last4: string;
      /** Last Used At */
      last_used_at: string | null;
      /** Name */
      name: string;
      /** Prefix */
      prefix: string;
      /** Revoked At */
      revoked_at: string | null;
      /** Scopes */
      scopes: "all"[];
    };
    /**
     * AccessTokenResponse
     * @description Token response used when the refresh token is stored in an HttpOnly cookie.
     */
    AccessTokenResponse: {
      /** Access Token */
      access_token: string;
      /**
       * Token Type
       * @default bearer
       */
      token_type: string;
    };
    /** AdminAccessKeyMetrics */
    AdminAccessKeyMetrics: {
      /** Active */
      active: number;
      /** Total */
      total: number;
      /** Used In Period */
      used_in_period: number;
    };
    /** AdminAnalyticsResponse */
    AdminAnalyticsResponse: {
      access_keys: components["schemas"]["AdminAccessKeyMetrics"];
      /** Daily */
      daily: components["schemas"]["AdminDailyAnalyticsPoint"][];
      /**
       * From
       * Format: date-time
       */
      from: string;
      profiles: components["schemas"]["AdminProfileMetrics"];
      searches: components["schemas"]["AdminSearchMetrics"];
      /**
       * Timezone
       * @default UTC
       * @constant
       */
      timezone: "UTC";
      /**
       * To
       * Format: date-time
       */
      to: string;
    };
    /** AdminAuditEventResponse */
    AdminAuditEventResponse: {
      /** Action */
      action: string;
      /** Actor Identifier */
      actor_identifier: string;
      /** Actor Type */
      actor_type: string;
      /** After State */
      after_state: {
        [key: string]: unknown;
      };
      /** Before State */
      before_state: {
        [key: string]: unknown;
      };
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Event Id
       * Format: uuid
       */
      event_id: string;
      /**
       * Target Email
       * Format: email
       */
      target_email: string;
      /** Target User Id */
      target_user_id: number | null;
    };
    /** AdminCapabilitiesResponse */
    AdminCapabilitiesResponse: {
      /** Can Manage Quotas */
      can_manage_quotas: boolean;
      /** Can View Analytics */
      can_view_analytics: boolean;
      /** Can View Operations */
      can_view_operations: boolean;
    };
    /** AdminDailyAnalyticsPoint */
    AdminDailyAnalyticsPoint: {
      /** Anonymous */
      anonymous: number;
      /** Authenticated */
      authenticated: number;
      /** Authenticated Mcp */
      authenticated_mcp: number;
      /** Authenticated Rest */
      authenticated_rest: number;
      /**
       * Day
       * Format: date
       */
      day: string;
      /** Standard */
      standard: number;
      /** Thorough */
      thorough: number;
      /** Total */
      total: number;
    };
    /** AdminIngestionIssue */
    AdminIngestionIssue: {
      /** Arxiv Id */
      arxiv_id: string;
      /** Attempt Count */
      attempt_count: number;
      /** Last Error Code */
      last_error_code: string | null;
      /** Last Error Message */
      last_error_message: string | null;
      /** Max Attempts */
      max_attempts: number;
      /**
       * Next Attempt At
       * Format: date-time
       */
      next_attempt_at: string;
      /**
       * Source
       * @enum {string}
       */
      source: "new" | "revision" | "reconciliation" | "backfill" | "manual";
      /**
       * Status
       * @enum {string}
       */
      status: "retry" | "dead";
      /** Target Version */
      target_version: number;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** AdminIntakePoint */
    AdminIntakePoint: {
      /**
       * Day
       * Format: date
       */
      day: string;
      /** Discovered */
      discovered: number;
      /** Full Text Completed */
      full_text_completed: number;
    };
    /** AdminOperationsResponse */
    AdminOperationsResponse: {
      /**
       * Generated At
       * Format: date-time
       */
      generated_at: string;
      /** Intake */
      intake: components["schemas"]["AdminIntakePoint"][];
      queue: components["schemas"]["AdminQueueState"];
      /** Recent Issues */
      recent_issues: components["schemas"]["AdminIngestionIssue"][];
      sync: components["schemas"]["AdminSyncState"] | null;
      /**
       * Timezone
       * @default UTC
       * @constant
       */
      timezone: "UTC";
    };
    /** AdminProfileMetrics */
    AdminProfileMetrics: {
      /** Active */
      active: number;
      /** Admins */
      admins: number;
      /** Blocked */
      blocked: number;
      /** Created In Period */
      created_in_period: number;
      /** Total */
      total: number;
    };
    /** AdminQueueState */
    AdminQueueState: {
      /** Dead */
      dead: number;
      /** Oldest Waiting At */
      oldest_waiting_at: string | null;
      /** Pending */
      pending: number;
      /** Retry */
      retry: number;
      /** Running */
      running: number;
      /** Succeeded */
      succeeded: number;
    };
    /** AdminQuotaResponse */
    AdminQuotaResponse: {
      /** Default Limit */
      default_limit: number;
      /** Effective Limit */
      effective_limit: number;
      /** Override Limit */
      override_limit: number | null;
      /** Remaining */
      remaining: number;
      /** Used */
      used: number;
    };
    /** AdminQuotasResponse */
    AdminQuotasResponse: {
      standard: components["schemas"]["AdminQuotaResponse"];
      survey: components["schemas"]["AdminQuotaResponse"];
      thorough: components["schemas"]["AdminQuotaResponse"];
    };
    /** AdminSearchMetrics */
    AdminSearchMetrics: {
      /** Anonymous */
      anonymous: number;
      /** Authenticated */
      authenticated: number;
      /** Authenticated Degraded */
      authenticated_degraded: number;
      /** Authenticated Failed */
      authenticated_failed: number;
      /** Authenticated Mcp */
      authenticated_mcp: number;
      /** Authenticated P50 Response Ms */
      authenticated_p50_response_ms: number | null;
      /** Authenticated P95 Response Ms */
      authenticated_p95_response_ms: number | null;
      /** Authenticated Rest */
      authenticated_rest: number;
      /** Authenticated Success */
      authenticated_success: number;
      /** Standard */
      standard: number;
      /** Thorough */
      thorough: number;
      /** Total */
      total: number;
    };
    /** AdminSyncState */
    AdminSyncState: {
      /** Last Error Code */
      last_error_code: string | null;
      /** Last Error Message */
      last_error_message: string | null;
      /** Last Started At */
      last_started_at: string | null;
      /** Last Succeeded At */
      last_succeeded_at: string | null;
      /** Last Successful Date */
      last_successful_date: string | null;
    };
    /** AdminUserLookupResponse */
    AdminUserLookupResponse: {
      quotas: components["schemas"]["AdminQuotasResponse"];
      user: components["schemas"]["AdminUserResponse"];
    };
    /** AdminUserResponse */
    AdminUserResponse: {
      /** Account Status */
      account_status: string;
      /** Display Name */
      display_name: string | null;
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Id */
      id: number;
    };
    /**
     * AvatarView
     * @description Short-lived authenticated view of a private avatar.
     */
    AvatarView: {
      /**
       * Expires At
       * Format: date-time
       */
      expires_at: string;
      /** Url */
      url: string;
      /**
       * Version
       * Format: uuid
       */
      version: string;
    };
    /**
     * BulkDeleteSearchHistoryRequest
     * @description Strict owner-scoped history IDs, stably deduplicated.
     */
    BulkDeleteSearchHistoryRequest: {
      /** Ids */
      ids: number[];
    };
    /**
     * BulkDeleteSearchHistoryResponse
     * @description Number of active owner-scoped rows soft-deleted by a bulk request.
     */
    BulkDeleteSearchHistoryResponse: {
      /** Deleted */
      deleted: number;
    };
    /** ChangePasswordRequest */
    ChangePasswordRequest: {
      /** Current Password */
      current_password: string;
      /** New Password */
      new_password: string;
    };
    /** CreateAccessKeyRequest */
    CreateAccessKeyRequest: {
      /** Expires At */
      expires_at?: string | null;
      /** Name */
      name: string;
      /** Scopes */
      scopes?: "all"[];
    };
    /** CreatedAccessKeyResponse */
    CreatedAccessKeyResponse: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Expires At */
      expires_at: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Key */
      key: string;
      /** Last4 */
      last4: string;
      /** Last Used At */
      last_used_at: string | null;
      /** Name */
      name: string;
      /** Prefix */
      prefix: string;
      /** Revoked At */
      revoked_at: string | null;
      /** Scopes */
      scopes: "all"[];
    };
    /** DailyQuotaUsage */
    DailyQuotaUsage: {
      /** Daily Limit */
      daily_limit: number;
      /** Remaining */
      remaining: number;
      /** Used */
      used: number;
    };
    /** DraftCreateRequest */
    DraftCreateRequest: {
      /**
       * Client Request Id
       * Format: uuid
       */
      client_request_id: string;
      /** Message */
      message: string;
    };
    /**
     * ExtractRequest
     * @description Start an extraction or continue one immutable cached result.
     */
    ExtractRequest: {
      /** Cookies */
      cookies?: {
        [key: string]: string;
      };
      /** Cursor */
      cursor?: string | null;
      /** Headers */
      headers?: {
        [key: string]: string;
      };
      /**
       * Max Chars
       * @default 20000
       */
      max_chars: number;
      /** @default main_markdown */
      output: components["schemas"]["ExtractResponseFormat"];
      /** @default auto */
      render: components["schemas"]["RenderMode"];
      /** Url */
      url?: string | null;
    };
    /**
     * ExtractResponse
     * @description One bounded page of an immutable extracted document.
     */
    ExtractResponse: {
      /** Author */
      author: string | null;
      /** Content */
      content: string;
      /** Content Hash */
      content_hash: string;
      /** Content Type */
      content_type: string;
      /** Extractor */
      extractor: string;
      /**
       * Fetched At
       * Format: date-time
       */
      fetched_at: string;
      /**
       * Final Url
       * Format: uri
       */
      final_url: string;
      /** Next Cursor */
      next_cursor: string | null;
      /** Published At */
      published_at: string | null;
      /** Rendered */
      rendered: boolean;
      /**
       * Requested Url
       * Format: uri
       */
      requested_url: string;
      /** Status Code */
      status_code: number;
      /** Title */
      title: string | null;
      /** Truncated */
      truncated: boolean;
      /** Warnings */
      warnings: string[];
    };
    /**
     * ExtractResponseFormat
     * @enum {string}
     */
    ExtractResponseFormat: "main_markdown" | "full_markdown" | "text" | "raw_html";
    /** ForgotPasswordRequest */
    ForgotPasswordRequest: {
      /**
       * Email
       * Format: email
       */
      email: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** LatencyPoint */
    LatencyPoint: {
      /**
       * Bucket Start
       * Format: date-time
       */
      bucket_start: string;
      /** Overall P95 Ms */
      overall_p95_ms: number | null;
      /** Sample Count */
      sample_count: number;
      /** Standard P50 Ms */
      standard_p50_ms: number | null;
      /** Thorough P50 Ms */
      thorough_p50_ms: number | null;
    };
    /** LatencyResponse */
    LatencyResponse: {
      /**
       * Bucket
       * @default day
       * @constant
       */
      bucket: "day";
      /**
       * From
       * Format: date-time
       */
      from: string;
      /** Points */
      points: components["schemas"]["LatencyPoint"][];
      /**
       * To
       * Format: date-time
       */
      to: string;
    };
    /** LoginRequest */
    LoginRequest: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
    };
    /** ManualDraftCreateRequest */
    ManualDraftCreateRequest: {
      /**
       * Client Request Id
       * Format: uuid
       */
      client_request_id: string;
      /** Markdown */
      markdown: string;
      /**
       * Message
       * @default Manual Draft revision
       */
      message: string;
    };
    /** MessageResponse */
    MessageResponse: {
      /** Message */
      message: string;
    };
    /**
     * PublicCapabilitiesResponse
     * @description Features that the public client may expose to this deployment.
     */
    PublicCapabilitiesResponse: {
      /**
       * Survey
       * @enum {string}
       */
      survey: "off" | "all";
    };
    /**
     * PublicSearchFilters
     * @description Filters supported by the public HTTP search contract.
     */
    PublicSearchFilters: {
      /** Authors */
      authors?: string[];
      /** Categories */
      categories?: string[];
      /** Date From */
      date_from?: string | null;
      /** Date To */
      date_to?: string | null;
    };
    /**
     * PublicSearchHistoryItem
     * @description One public history item without internal strategy or level fields.
     */
    PublicSearchHistoryItem: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Elapsed Ms */
      elapsed_ms: number;
      filters: components["schemas"]["PublicSearchFilters"];
      /** Id */
      id: number;
      /** Query */
      query: string;
      /** Result Count */
      result_count: number;
      strength: components["schemas"]["SearchStrength"];
    };
    /**
     * PublicSearchHistoryPage
     * @description A paginated search-history response with an exact snapshot total.
     */
    PublicSearchHistoryPage: {
      /** Items */
      items: components["schemas"]["PublicSearchHistoryItem"][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /**
     * PublicSearchHit
     * @description A ranked paper result without internal search diagnostics.
     */
    PublicSearchHit: {
      /** Abstract */
      abstract: string | null;
      /** Arxiv Id */
      arxiv_id: string;
      /**
       * Arxiv Url
       * Format: uri
       */
      arxiv_url: string;
      /** Authors */
      authors: string[];
      /** Categories */
      categories: string[];
      /**
       * Pdf Url
       * Format: uri
       */
      pdf_url: string;
      /**
       * Rank
       * @description Authoritative order within this response.
       */
      rank: number;
      /**
       * Score
       * @description Unnormalized retrieval signal; compare only within the current response, never across queries, strengths, indexes, models, or time.
       */
      score: number;
      /** Submitted At */
      submitted_at: string | null;
      /** Title */
      title: string;
      /** Updated At */
      updated_at: string | null;
      /** Version */
      version: number | null;
    };
    /**
     * PublicSearchRequest
     * @description Stable public search input, isolated from internal pipeline controls.
     * @example {
     *       "filters": {
     *         "authors": [],
     *         "categories": [
     *           "cs.AI",
     *           "cs.IR"
     *         ],
     *         "date_from": "2020-01-01"
     *       },
     *       "limit": 10,
     *       "query": "retrieval augmented generation",
     *       "strength": "standard"
     *     }
     */
    PublicSearchRequest: {
      filters?: components["schemas"]["PublicSearchFilters"];
      /**
       * Limit
       * @default 10
       */
      limit: number;
      /** Query */
      query: string;
      /** @default standard */
      strength: components["schemas"]["SearchStrength"];
    };
    /**
     * PublicSearchResponse
     * @description Public search response; rank is authoritative and score is unnormalized.
     * @example {
     *       "degraded": true,
     *       "elapsed_ms": 842.37,
     *       "hits": [
     *         {
     *           "arxiv_id": "2401.12345",
     *           "arxiv_url": "https://arxiv.org/abs/2401.12345",
     *           "authors": [
     *             "Example Author"
     *           ],
     *           "categories": [
     *             "cs.AI",
     *             "cs.IR"
     *           ],
     *           "pdf_url": "https://arxiv.org/pdf/2401.12345",
     *           "rank": 1,
     *           "score": 12.75,
     *           "submitted_at": "2024-01-20T00:00:00Z",
     *           "title": "A Paper About Retrieval",
     *           "updated_at": "2024-03-05T00:00:00Z",
     *           "version": 2
     *         }
     *       ],
     *       "query": "retrieval augmented generation",
     *       "result_count": 1,
     *       "strength": "standard"
     *     }
     */
    PublicSearchResponse: {
      /** Degraded */
      degraded: boolean;
      /** Elapsed Ms */
      elapsed_ms: number;
      /** Hits */
      hits: components["schemas"]["PublicSearchHit"][];
      /** Query */
      query: string;
      /** Result Count */
      result_count: number;
      strength: components["schemas"]["SearchStrength"];
    };
    /** QuotaOverrideRequest */
    QuotaOverrideRequest: {
      /** Standard */
      standard: number | null;
      /** Survey */
      survey: number | null;
      /** Thorough */
      thorough: number | null;
    };
    /** QuotaOverrideUpdateResponse */
    QuotaOverrideUpdateResponse: {
      /** Changed */
      changed: boolean;
    };
    /** RegisterRequest */
    RegisterRequest: {
      /** Display Name */
      display_name?: string | null;
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
    };
    /**
     * RenderMode
     * @enum {string}
     */
    RenderMode: "auto" | "never" | "always";
    /** ResetPasswordRequest */
    ResetPasswordRequest: {
      /** New Password */
      new_password: string;
      /** Token */
      token: string;
    };
    /**
     * SearchStrength
     * @description Public search quality presets.
     * @enum {string}
     */
    SearchStrength: "standard" | "thorough";
    /** SessionResponse */
    SessionResponse: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Current */
      current: boolean;
      /**
       * Expires At
       * Format: date-time
       */
      expires_at: string;
      /** Id */
      id: number;
      /**
       * Last Seen At
       * Format: date-time
       */
      last_seen_at: string;
      /** User Agent */
      user_agent?: string | null;
    };
    /** SurveyActionRequest */
    SurveyActionRequest: {
      /**
       * Client Request Id
       * Format: uuid
       */
      client_request_id: string;
      /**
       * Notify On Completion
       * @default false
       */
      notify_on_completion: boolean;
    };
    /** SurveyArtifactItemResponse */
    SurveyArtifactItemResponse: {
      /** Content Type */
      content_type: string;
      /** Download Url */
      download_url: string;
      /** Path */
      path: string;
      /** Sha256 */
      sha256: string;
      /** Size */
      size: number;
    };
    /** SurveyArtifactsResponse */
    SurveyArtifactsResponse: {
      /**
       * Expires At
       * Format: date-time
       */
      expires_at: string;
      /** Items */
      items: components["schemas"]["SurveyArtifactItemResponse"][];
      /**
       * Survey Id
       * Format: uuid
       */
      survey_id: string;
    };
    /** SurveyCreateRequest */
    SurveyCreateRequest: {
      /**
       * Client Request Id
       * Format: uuid
       */
      client_request_id: string;
      /** Initial Request */
      initial_request: string;
    };
    /** SurveyDraftResponse */
    SurveyDraftResponse: {
      /** Based On Revision */
      based_on_revision: number | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Error Code */
      error_code: string | null;
      /** Error Message */
      error_message: string | null;
      /** Finished At */
      finished_at: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Markdown */
      markdown: string | null;
      /** Revision */
      revision: number | null;
      /** Source */
      source: string;
      /** Started At */
      started_at: string | null;
      /** Status */
      status: string;
      /** User Message */
      user_message: string;
    };
    /** SurveyListResponse */
    SurveyListResponse: {
      /** Items */
      items: components["schemas"]["SurveySummaryResponse"][];
      /** Next Cursor */
      next_cursor: string | null;
      quota: components["schemas"]["SurveyQuotaResponse"];
    };
    /** SurveyProgressResponse */
    SurveyProgressResponse: {
      /** Elapsed Seconds */
      elapsed_seconds: number;
      /** Finished At */
      finished_at: string | null;
      /**
       * Last Activity At
       * Format: date-time
       */
      last_activity_at: string;
      /** Percent */
      percent: number;
      queue: components["schemas"]["SurveyQueueResponse"] | null;
      /**
       * Stage
       * @enum {string}
       */
      stage:
        | "drafting"
        | "waiting_for_draft"
        | "waiting_for_execution"
        | "planning"
        | "discovering"
        | "reviewing_evidence"
        | "structuring_report"
        | "writing_report"
        | "finalizing"
        | "cancelling"
        | "saving_results"
        | "completed"
        | "failed"
        | "cancelled";
      /** Started At */
      started_at: string | null;
      /** Status */
      status: string;
      /** Step */
      step: number;
      /**
       * Survey Id
       * Format: uuid
       */
      survey_id: string;
      /** Total Steps */
      total_steps: number;
    };
    /** SurveyQueueResponse */
    SurveyQueueResponse: {
      /** Kind */
      kind: string;
      /** Max Slots */
      max_slots: number;
      /** Position */
      position: number;
      /**
       * Queued At
       * Format: date-time
       */
      queued_at: string;
      /** Running Slots */
      running_slots: number;
    };
    /** SurveyQuotaResponse */
    SurveyQuotaResponse: {
      /** Daily Limit */
      daily_limit: number;
      /** Remaining */
      remaining: number;
      /** Reserved */
      reserved: number;
      /** Succeeded */
      succeeded: number;
    };
    /** SurveyResponse */
    SurveyResponse: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Error Code */
      error_code: string | null;
      /** Error Message */
      error_message: string | null;
      /** Finished At */
      finished_at: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Initial Request */
      initial_request: string;
      /** Quota State */
      quota_state: string;
      /** Started At */
      started_at: string | null;
      /** Status */
      status: string;
      /** Title */
      title: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** SurveySummaryResponse */
    SurveySummaryResponse: {
      /** Artifacts Available */
      artifacts_available: boolean;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Error Code */
      error_code: string | null;
      /** Error Message */
      error_message: string | null;
      /** Finished At */
      finished_at: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Latest Draft Revision */
      latest_draft_revision: number | null;
      progress: components["schemas"]["SurveyProgressResponse"];
      /** Report Available */
      report_available: boolean;
      /** Started At */
      started_at: string | null;
      /** Status */
      status: string;
      /** Title */
      title: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** TodayUsage */
    TodayUsage: {
      standard: components["schemas"]["DailyQuotaUsage"];
      survey: components["schemas"]["DailyQuotaUsage"];
      thorough: components["schemas"]["DailyQuotaUsage"];
    };
    /** UpdateAccessKeyRequest */
    UpdateAccessKeyRequest: {
      /** Expires At */
      expires_at?: string | null;
      /** Name */
      name?: string | null;
    };
    /**
     * UpdateProfileBody
     * @description Body for ``PUT``/``PATCH /profile`` — only supplied fields are updated.
     */
    UpdateProfileBody: {
      /** Display Name */
      display_name?: string | null;
    };
    /** UsageAccessKey */
    UsageAccessKey: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Last4 */
      last4: string;
      /** Name */
      name: string;
    };
    /** UsageRecord */
    UsageRecord: {
      access_key: components["schemas"]["UsageAccessKey"] | null;
      /**
       * Actor Type
       * @enum {string}
       */
      actor_type: "web" | "access_key" | "delegated";
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Error Code */
      error_code: string | null;
      /** Id */
      id: number;
      /**
       * Outcome
       * @enum {string}
       */
      outcome: "success" | "degraded" | "failed";
      /** Quota Units */
      quota_units: number;
      /** Result Count */
      result_count: number | null;
      /** Search Duration Ms */
      search_duration_ms: number | null;
      /** Status Code */
      status_code: number | null;
      /**
       * Strength
       * @enum {string}
       */
      strength: "standard" | "thorough";
    };
    /** UsageRecordsResponse */
    UsageRecordsResponse: {
      /** Items */
      items: components["schemas"]["UsageRecord"][];
      /** Next Cursor */
      next_cursor: string | null;
    };
    /** UsageSummaryResponse */
    UsageSummaryResponse: {
      /** Degraded Count */
      degraded_count: number;
      /** Failed Count */
      failed_count: number;
      /** P95 Response Ms */
      p95_response_ms: number | null;
      /**
       * Reset At
       * Format: date-time
       */
      reset_at: string;
      /** Searches This Month */
      searches_this_month: number;
      /** Searches Today */
      searches_today: number;
      /** Success Rate */
      success_rate: number | null;
      /**
       * Timezone
       * @default UTC
       * @constant
       */
      timezone: "UTC";
      today: components["schemas"]["TodayUsage"];
      /** Typical Response Ms */
      typical_response_ms: number | null;
    };
    /** UserPublic */
    UserPublic: {
      /** Created At */
      created_at?: string | null;
      /** Display Name */
      display_name?: string | null;
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Email Verified */
      email_verified: boolean;
      /** Id */
      id: number;
      /**
       * Status
       * @enum {string}
       */
      status: "pending_verification" | "active" | "disabled" | "locked";
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** VerifyEmailRequest */
    VerifyEmailRequest: {
      /** Token */
      token: string;
    };
    /** VolumePoint */
    VolumePoint: {
      /**
       * Bucket Start
       * Format: date-time
       */
      bucket_start: string;
      /** Standard */
      standard: number;
      /** Thorough */
      thorough: number;
    };
    /** VolumeResponse */
    VolumeResponse: {
      /**
       * Bucket
       * @default day
       * @constant
       */
      bucket: "day";
      /**
       * From
       * Format: date-time
       */
      from: string;
      /** Points */
      points: components["schemas"]["VolumePoint"][];
      /**
       * To
       * Format: date-time
       */
      to: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  analytics_overview_admin_analytics_overview_get: {
    parameters: {
      query?: {
        days?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminAnalyticsResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  audit_events_admin_audit_events_get: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminAuditEventResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  capabilities_admin_capabilities_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminCapabilitiesResponse"];
        };
      };
    };
  };
  operations_overview_admin_operations_overview_get: {
    parameters: {
      query?: {
        days?: number;
        issue_limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminOperationsResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  lookup_user_admin_users_lookup_get: {
    parameters: {
      query: {
        email: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminUserLookupResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_quota_overrides_admin_users__user_id__quota_overrides_put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["QuotaOverrideRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["QuotaOverrideUpdateResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  change_password_auth_change_password_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangePasswordRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  _forgot_password_auth_forgot_password_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ForgotPasswordRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  _login_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccessTokenResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  logout_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
    };
  };
  _refresh_cookie_auth_refresh_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccessTokenResponse"];
        };
      };
    };
  };
  _register_auth_register_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  _resend_verification_auth_resend_verification_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ForgotPasswordRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  _reset_password_auth_reset_password_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResetPasswordRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_sessions_auth_sessions_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionResponse"][];
        };
      };
    };
  };
  revoke_others_auth_sessions_revoke_others_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
    };
  };
  delete_session_auth_sessions__session_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  verify_email_auth_verify_email_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VerifyEmailRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_capabilities_capabilities_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PublicCapabilitiesResponse"];
        };
      };
    };
  };
  extract_extract_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ExtractRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExtractResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string | null;
          };
        };
      };
    };
  };
  livez_livez_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  readyz_readyz_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  search_search_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PublicSearchRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PublicSearchResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_history_search_history_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
        q?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PublicSearchHistoryPage"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  bulk_delete_history_search_history_bulk_delete_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BulkDeleteSearchHistoryRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BulkDeleteSearchHistoryResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_history_entry_search_history__entry_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        entry_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  surveys_surveys_get: {
    parameters: {
      query?: {
        view?: "active" | "completed" | "all";
        limit?: number;
        cursor?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SurveyListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  submit_survey_surveys_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SurveyCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SurveyResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  survey_surveys__survey_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        survey_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SurveyResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  remove_survey_surveys__survey_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        survey_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  survey_artifacts_surveys__survey_id__artifacts_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        survey_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SurveyArtifactsResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  cancel_survey_request_surveys__survey_id__cancel_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        survey_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SurveyResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  survey_report_download_surveys__survey_id__download_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        survey_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/zip": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  survey_drafts_surveys__survey_id__drafts_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        survey_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SurveyDraftResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  revise_survey_draft_surveys__survey_id__drafts_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        survey_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DraftCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SurveyDraftResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  add_manual_survey_draft_surveys__survey_id__drafts_manual_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        survey_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ManualDraftCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SurveyDraftResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  survey_progress_surveys__survey_id__progress_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        survey_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SurveyProgressResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  survey_report_surveys__survey_id__report_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        survey_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  start_survey_execution_surveys__survey_id__start_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        survey_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SurveyActionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SurveyResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_keys_user_access_keys_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccessKeyResponse"][];
        };
      };
    };
  };
  create_key_user_access_keys_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateAccessKeyRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreatedAccessKeyResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_key_user_access_keys__key_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  patch_key_user_access_keys__key_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateAccessKeyRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccessKeyResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_avatar_user_avatar_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AvatarView"];
        };
      };
    };
  };
  get_profile_user_profile_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserPublic"];
        };
      };
    };
  };
  _update_profile_user_profile_put: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateProfileBody"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserPublic"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  _update_profile_user_profile_patch: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateProfileBody"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserPublic"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  usage_export_user_usage_export_csv_get: {
    parameters: {
      query?: {
        strength?: ("standard" | "thorough") | null;
        actor_type?: ("web" | "access_key" | "delegated") | null;
        access_key_id?: string | null;
        outcome?: ("success" | "degraded" | "failed") | null;
        from?: string | null;
        to?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Usage records exported as CSV. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/csv": string;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  usage_latency_user_usage_latency_get: {
    parameters: {
      query?: {
        from?: string | null;
        to?: string | null;
        bucket?: "day";
        access_key_id?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LatencyResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  usage_records_user_usage_records_get: {
    parameters: {
      query?: {
        cursor?: string | null;
        limit?: number;
        strength?: ("standard" | "thorough") | null;
        actor_type?: ("web" | "access_key" | "delegated") | null;
        access_key_id?: string | null;
        outcome?: ("success" | "degraded" | "failed") | null;
        from?: string | null;
        to?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UsageRecordsResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  usage_summary_user_usage_summary_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UsageSummaryResponse"];
        };
      };
    };
  };
  usage_volume_user_usage_volume_get: {
    parameters: {
      query?: {
        from?: string | null;
        to?: string | null;
        bucket?: "day";
        access_key_id?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VolumeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
